import { TestBed } from '@angular/core/testing';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { of } from 'rxjs';

// Mock translate loader
export class MockTranslateLoader implements TranslateLoader {
  getTranslation() {
    return of({
      'COMMON.AGE': 'Edat',
      'COMMON.PRICE': 'Preu',
      'COMMON.QUANTITY': 'Quantitat',
      'INPUTS.NUMBER_PLACEHOLDER': 'Introdueix un número...',
      'COMMON.NAME': 'Nom',
      'COMMON.EMAIL': 'Email',
      'COMMON.PASSWORD': 'Contrasenya',
      'COMMON.SUBMIT': 'Enviar',
      'COMMON.CANCEL': 'Cancel·lar',
      'COMMON.SAVE': 'Desar',
      'COMMON.DELETE': 'Eliminar',
      'COMMON.EDIT': 'Editar',
      'COMMON.VIEW': 'Veure',
      'COMMON.CLOSE': 'Tancar',
      'COMMON.OPEN': 'Obrir',
      'COMMON.SEARCH': 'Buscar',
      'COMMON.FILTER': 'Filtrar',
      'COMMON.SORT': 'Ordenar',
      'COMMON.REFRESH': 'Actualitzar',
      'COMMON.LOADING': 'Carregant...',
      'COMMON.ERROR': 'Error',
      'COMMON.SUCCESS': 'Èxit',
      'COMMON.WARNING': 'Advertència',
      'COMMON.INFO': 'Informació',
      'COMMON.CONFIRM': 'Confirmar',
      'COMMON.YES': 'Sí',
      'COMMON.NO': 'No',
      'COMMON.OK': 'D\'acord',
      'COMMON.BACK': 'Enrere',
      'COMMON.NEXT': 'Següent',
      'COMMON.PREVIOUS': 'Anterior',
      'COMMON.FIRST': 'Primer',
      'COMMON.LAST': 'Últim',
      'COMMON.ALL': 'Tots',
      'COMMON.NONE': 'Cap',
      'COMMON.SELECT': 'Seleccionar',
      'COMMON.CLEAR': 'Netejar',
      'COMMON.RESET': 'Restablir',
      'COMMON.APPLY': 'Aplicar',
      'COMMON.ACCEPT': 'Acceptar',
      'COMMON.REJECT': 'Rebutjar',
      'COMMON.APPROVE': 'Aprovar',
      'COMMON.DENY': 'Denegar',
      'COMMON.ACTIVATE': 'Activar',
      'COMMON.DEACTIVATE': 'Desactivar',
      'COMMON.ENABLE': 'Habilitar',
      'COMMON.DISABLE': 'Deshabilitar',
      'COMMON.SHOW': 'Mostrar',
      'COMMON.HIDE': 'Amagar',
      'COMMON.EXPAND': 'Expandir',
      'COMMON.COLLAPSE': 'Col·lapsar',
      'COMMON.MINIMIZE': 'Minimitzar',
      'COMMON.MAXIMIZE': 'Maximitzar',
      'COMMON.FULLSCREEN': 'Pantalla completa',
      'COMMON.EXIT_FULLSCREEN': 'Sortir de pantalla completa',
      'COMMON.ZOOM_IN': 'Ampliar',
      'COMMON.ZOOM_OUT': 'Reduir',
      'COMMON.ROTATE': 'Rotar',
      'COMMON.FLIP': 'Girar',
      'COMMON.CROP': 'Retallar',
      'COMMON.RESIZE': 'Redimensionar',
      'COMMON.MOVE': 'Moure',
      'COMMON.COPY': 'Copiar',
      'COMMON.PASTE': 'Enganxar',
      'COMMON.CUT': 'Tallar',
      'COMMON.UNDO': 'Desfer',
      'COMMON.REDO': 'Refer',
      'COMMON.SELECT_ALL': 'Seleccionar tot',
      'COMMON.DESELECT_ALL': 'Deseleccionar tot',
      'COMMON.INVERT_SELECTION': 'Invertir selecció',
      'COMMON.ADD': 'Afegir',
      'COMMON.REMOVE': 'Eliminar',
      'COMMON.INSERT': 'Inserir',
      'COMMON.UPDATE': 'Actualitzar',
      'COMMON.CREATE': 'Crear',
      'COMMON.DESTROY': 'Destruir',
      'COMMON.BUILD': 'Construir',
      'COMMON.DEPLOY': 'Desplegar',
      'COMMON.TEST': 'Provar',
      'COMMON.DEBUG': 'Depurar',
      'COMMON.LOG': 'Registre',
      'COMMON.EXPORT': 'Exportar',
      'COMMON.IMPORT': 'Importar',
      'COMMON.DOWNLOAD': 'Descarregar',
      'COMMON.UPLOAD': 'Pujar',
      'COMMON.SYNC': 'Sincronitzar',
      'COMMON.BACKUP': 'Còpia de seguretat',
      'COMMON.RESTORE': 'Restaurar',
      'COMMON.ARCHIVE': 'Arxivar',
      'COMMON.UNARCHIVE': 'Desarxivar',
      'COMMON.PIN': 'Fixar',
      'COMMON.UNPIN': 'Desfixar',
      'COMMON.STAR': 'Marcar com a favorit',
      'COMMON.UNSTAR': 'Desmarcar com a favorit',
      'COMMON.LIKE': 'M\'agrada',
      'COMMON.UNLIKE': 'No m\'agrada',
      'COMMON.SHARE': 'Compartir',
      'COMMON.SEND': 'Enviar',
      'COMMON.RECEIVE': 'Rebre',
      'COMMON.READ': 'Llegir',
      'COMMON.WRITE': 'Escriure',
      'COMMON.PRINT': 'Imprimir',
      'COMMON.SCAN': 'Escanejar',
      'COMMON.FAX': 'Fax',
      'COMMON.CALL': 'Trucar',
      'COMMON.HANG_UP': 'Penjar',
      'COMMON.ANSWER': 'Contestar',
      'COMMON.IGNORE': 'Ignorar',
      'COMMON.BLOCK': 'Bloquejar',
      'COMMON.UNBLOCK': 'Desbloquejar',
      'COMMON.MUTE': 'Silenciar',
      'COMMON.UNMUTE': 'Activar so',
      'COMMON.PAUSE': 'Pausar',
      'COMMON.PLAY': 'Reproduir',
      'COMMON.STOP': 'Aturar',
      'COMMON.SKIP': 'Saltar',
      'COMMON.REWIND': 'Rebobinar',
      'COMMON.FAST_FORWARD': 'Avançar ràpid',
      'COMMON.RECORD': 'Enregistrar',
      'COMMON.LIVE': 'En directe',
      'COMMON.SCHEDULE': 'Programar',
      'COMMON.REMIND': 'Recordar',
      'COMMON.NOTIFY': 'Notificar',
      'COMMON.ALERT': 'Alerta',
      'COMMON.BELL': 'Campana',
      'COMMON.SETTINGS': 'Configuració',
      'COMMON.PREFERENCES': 'Preferències',
      'COMMON.PROFILE': 'Perfil',
      'COMMON.ACCOUNT': 'Compte',
      'COMMON.SECURITY': 'Seguretat',
      'COMMON.PRIVACY': 'Privadesa',
      'COMMON.HELP': 'Ajuda',
      'COMMON.SUPPORT': 'Suport',
      'COMMON.FEEDBACK': 'Comentaris',
      'COMMON.REPORT': 'Informar',
      'COMMON.ISSUE': 'Problema',
      'COMMON.BUG': 'Error',
      'COMMON.ENHANCEMENT': 'Millora',
      'COMMON.REQUEST': 'Sol·licitud',
      'COMMON.SUGGESTION': 'Suggeriment',
      'COMMON.QUESTION': 'Pregunta',
      'COMMON.SOLUTION': 'Solució',
      'COMMON.WORKAROUND': 'Alternativa',
      'COMMON.FIX': 'Correcció',
      'COMMON.PATCH': 'Pedaç',
      'COMMON.UPGRADE': 'Actualització',
      'COMMON.DOWNGRADE': 'Downgrade',
      'COMMON.INSTALL': 'Instal·lar',
      'COMMON.UNINSTALL': 'Desinstal·lar',
      'COMMON.CONFIGURE': 'Configurar',
      'COMMON.SETUP': 'Configuració',
      'COMMON.INITIALIZE': 'Inicialitzar',
      'COMMON.START': 'Iniciar',
      'COMMON.RESTART': 'Reiniciar',
      'COMMON.SHUTDOWN': 'Apagar',
      'COMMON.SLEEP': 'Dormir',
      'COMMON.WAKE': 'Despertar',
      'COMMON.LOCK': 'Bloquejar',
      'COMMON.UNLOCK': 'Desbloquejar',
      'COMMON.LOGIN': 'Iniciar sessió',
      'COMMON.LOGOUT': 'Tancar sessió',
      'COMMON.REGISTER': 'Registrar-se',
      'COMMON.SIGN_UP': 'Registrar-se',
      'COMMON.SIGN_IN': 'Iniciar sessió',
      'COMMON.SIGN_OUT': 'Tancar sessió',
      'COMMON.FORGOT_PASSWORD': 'He oblidat la contrasenya',
      'COMMON.RESET_PASSWORD': 'Restablir contrasenya',
      'COMMON.CHANGE_PASSWORD': 'Canviar contrasenya',
      'COMMON.VERIFY_EMAIL': 'Verificar email',
      'COMMON.CONFIRM_EMAIL': 'Confirmar email',
      'COMMON.RESEND_EMAIL': 'Reenviar email',
      'COMMON.ACTIVATE_ACCOUNT': 'Activar compte',
      'COMMON.DEACTIVATE_ACCOUNT': 'Desactivar compte',
      'COMMON.DELETE_ACCOUNT': 'Eliminar compte',
      'COMMON.SUSPEND_ACCOUNT': 'Suspendre compte',
      'COMMON.REACTIVATE_ACCOUNT': 'Reactivar compte',
      'COMMON.BAN_USER': 'Bannejar usuari',
      'COMMON.UNBAN_USER': 'Desbannejar usuari',
      'COMMON.MUTE_USER': 'Silenciar usuari',
      'COMMON.UNMUTE_USER': 'Activar so usuari',
      'COMMON.FOLLOW': 'Seguir',
      'COMMON.UNFOLLOW': 'Deixar de seguir',
      'COMMON.SUBSCRIBE': 'Subscriure\'s',
      'COMMON.UNSUBSCRIBE': 'Desubscriure\'s',
      'COMMON.JOIN': 'Unir-se',
      'COMMON.LEAVE': 'Sortir',
      'COMMON.INVITE': 'Convidar',
      'COMMON.ACCEPT_INVITE': 'Acceptar convit',
      'COMMON.DECLINE_INVITE': 'Rebutjar convit',
      'COMMON.REQUEST_JOIN': 'Sol·licitar unió',
      'COMMON.APPROVE_REQUEST': 'Aprovar sol·licitud',
      'COMMON.DENY_REQUEST': 'Denegar sol·licitud',
      'COMMON.ASSIGN': 'Assignar',
      'COMMON.UNASSIGN': 'Desassignar',
      'COMMON.PROMOTE': 'Promocionar',
      'COMMON.DEMOTE': 'Degradar',
      'COMMON.GRANT': 'Concedir',
      'COMMON.REVOKE': 'Revocar',
      'COMMON.AUTHORIZE': 'Autoritzar',
      'COMMON.UNAUTHORIZE': 'Desautoritzar',
      'COMMON.VERIFY': 'Verificar',
      'COMMON.UNVERIFY': 'Desverificar',
      'COMMON.PUBLISH': 'Publicar',
      'COMMON.UNPUBLISH': 'Despublicar',
      'COMMON.FEATURE': 'Destacar',
      'COMMON.UNFEATURE': 'No destacar',
      'COMMON.STICKY': 'Fixar',
      'COMMON.UNSTICKY': 'Desfixar',
      'COMMON.MERGE': 'Fusionar',
      'COMMON.SPLIT': 'Dividir',
      'COMMON.DUPLICATE': 'Duplicar',
      'COMMON.CLONE': 'Clonar',
      'COMMON.FORK': 'Bifurcar',
      'COMMON.BRANCH': 'Branca',
      'COMMON.MERGE_BRANCH': 'Fusionar branca',
      'COMMON.DELETE_BRANCH': 'Eliminar branca',
      'COMMON.CREATE_BRANCH': 'Crear branca',
      'COMMON.SWITCH_BRANCH': 'Canviar branca',
      'COMMON.COMMIT': 'Commit',
      'COMMON.PUSH': 'Pujar',
      'COMMON.PULL': 'Descarregar',
      'COMMON.FETCH': 'Obtenir',
      'COMMON.CHECKOUT': 'Checkout',
      'COMMON.REVERT': 'Revertir',
      'COMMON.CHERRY_PICK': 'Cherry pick',
      'COMMON.SQUASH': 'Squash',
      'COMMON.REBASE': 'Rebase',
      'COMMON.STASH': 'Stash',
      'COMMON.POP': 'Pop',
      'COMMON.DROP': 'Eliminar',
      'COMMON.CLEAN': 'Netejar',
      'COMMON.RELEASE': 'Alliberar',
      'COMMON.TAG': 'Etiqueta',
      'COMMON.VERSION': 'Versió',
      'COMMON.CHANGELOG': 'Registre de canvis',
      'COMMON.README': 'Llegiu-me',
      'COMMON.LICENSE': 'Llicència',
      'COMMON.CONTRIBUTING': 'Contribuint',
      'COMMON.CODE_OF_CONDUCT': 'Codi de conducta',
      'COMMON.PRIVACY_POLICY': 'Política de privadesa',
      'COMMON.TERMS_OF_SERVICE': 'Termes de servei',
      'COMMON.CONTACT': 'Contacte',
      'COMMON.ABOUT': 'Sobre',
      'COMMON.FAQ': 'Preguntes freqüents',
      'COMMON.DOCUMENTATION': 'Documentació',
      'COMMON.API': 'API',
      'COMMON.SDK': 'SDK',
      'COMMON.LIBRARY': 'Biblioteca',
      'COMMON.FRAMEWORK': 'Framework',
      'COMMON.PLUGIN': 'Plugin',
      'COMMON.EXTENSION': 'Extensió',
      'COMMON.THEME': 'Tema',
      'COMMON.TEMPLATE': 'Plantilla',
      'COMMON.WIDGET': 'Widget',
      'COMMON.COMPONENT': 'Component',
      'COMMON.SERVICE': 'Servei',
      'COMMON.MODULE': 'Mòdul',
      'COMMON.PACKAGE': 'Paquet',
      'COMMON.DEPENDENCY': 'Dependència',
      'COMMON.DEV_DEPENDENCY': 'Dependència de desenvolupament',
      'COMMON.PEER_DEPENDENCY': 'Dependència peer',
      'COMMON.OPTIONAL_DEPENDENCY': 'Dependència opcional',
      'COMMON.BUNDLE': 'Bundle',
      'COMMON.CHUNK': 'Chunk',
      'COMMON.ASSET': 'Actiu',
      'COMMON.RESOURCE': 'Recurs',
      'COMMON.CONFIG': 'Configuració',
      'COMMON.ENV': 'Entorn',
      'COMMON.DEV': 'Desenvolupament',
      'COMMON.PROD': 'Producció',
      'COMMON.STAGING': 'Staging',
      'COMMON.TESTING': 'Proves',
      'COMMON.TRACE': 'Traça',
      'COMMON.FATAL': 'Fatal',
      'COMMON.CRITICAL': 'Crític',
      'COMMON.EMERGENCY': 'Emergència',
      'COMMON.NOTICE': 'Avís',
      'COMMON.FAILURE': 'Fallada',
      'COMMON.EXCEPTION': 'Excepció',
      'COMMON.THROW': 'Llançar',
      'COMMON.CATCH': 'Capturar',
      'COMMON.FINALLY': 'Finalment',
      'COMMON.TRY': 'Intentar',
      'COMMON.ELSE': 'Altrament',
      'COMMON.IF': 'Si',
      'COMMON.THEN': 'Llavors',
      'COMMON.WHILE': 'Mentre',
      'COMMON.FOR': 'Per',
      'COMMON.DO': 'Fer',
      'COMMON.SWITCH': 'Canviar',
      'COMMON.CASE': 'Cas',
      'COMMON.DEFAULT': 'Per defecte',
      'COMMON.BREAK': 'Interrompre',
      'COMMON.CONTINUE': 'Continuar',
      'COMMON.RETURN': 'Retornar',
      'COMMON.YIELD': 'Cedir',
      'COMMON.AWAIT': 'Esperar',
      'COMMON.ASYNC': 'Asíncron',
      'COMMON.PROMISE': 'Promesa',
      'COMMON.OBSERVABLE': 'Observable',
      'COMMON.SUBJECT': 'Subjecte',
      'COMMON.BEHAVIOR_SUBJECT': 'Subjecte de comportament',
      'COMMON.REPLAY_SUBJECT': 'Subjecte de repetició',
      'COMMON.ASYNC_SUBJECT': 'Subjecte asíncron',
      'COMMON.OPERATOR': 'Operador',
      'COMMON.PIPE': 'Tub',
      'COMMON.MAP': 'Mapa',
      'COMMON.REDUCE': 'Reduir',
      'COMMON.CONCAT': 'Concatenar',
      'COMMON.COMBINE_LATEST': 'Combinar últim',
      'COMMON.WITH_LATEST_FROM': 'Amb últim de',
      'COMMON.SWITCH_MAP': 'Canviar mapa',
      'COMMON.MERGE_MAP': 'Fusionar mapa',
      'COMMON.CONCAT_MAP': 'Concatenar mapa',
      'COMMON.EXHAUST_MAP': 'Esgotar mapa',
      'COMMON.DEBOUNCE': 'Debounce',
      'COMMON.THROTTLE': 'Throttle',
      'COMMON.DISTINCT': 'Distint',
      'COMMON.DISTINCT_UNTIL_CHANGED': 'Distint fins que canviï',
      'COMMON.DISTINCT_UNTIL_KEY_CHANGED': 'Distint fins que canviï clau',
      'COMMON.SKIP_UNTIL': 'Saltar fins',
      'COMMON.SKIP_WHILE': 'Saltar mentre',
      'COMMON.TAKE_UNTIL': 'Prendre fins',
      'COMMON.TAKE_WHILE': 'Prendre mentre',
      'COMMON.TAKE_LAST': 'Prendre últim',
      'COMMON.SINGLE': 'Únic',
      'COMMON.ELEMENT_AT': 'Element a',
      'COMMON.FIND': 'Trobar',
      'COMMON.FIND_INDEX': 'Trobar índex',
      'COMMON.INDEX_OF': 'Índex de',
      'COMMON.LAST_INDEX_OF': 'Últim índex de',
      'COMMON.INCLUDES': 'Inclou',
      'COMMON.SOME': 'Alguns',
      'COMMON.EVERY': 'Tots',
      'COMMON.IS_EMPTY': 'Està buit',
      'COMMON.DEFAULT_IF_EMPTY': 'Per defecte si està buit',
      'COMMON.SWITCH_IF_EMPTY': 'Canviar si està buit',
      'COMMON.START_WITH': 'Començar amb',
      'COMMON.END_WITH': 'Acabar amb',
      'COMMON.REPEAT': 'Repetir',
      'COMMON.REPEAT_WHEN': 'Repetir quan',
      'COMMON.RETRY': 'Reintentar',
      'COMMON.RETRY_WHEN': 'Reintentar quan',
      'COMMON.CATCH_ERROR': 'Capturar error',
      'COMMON.FINALIZE': 'Finalitzar',
      'COMMON.TAP': 'Tocar',
      'COMMON.DELAY': 'Retard',
      'COMMON.DELAY_WHEN': 'Retard quan',
      'COMMON.TIMEOUT': 'Temps d\'espera',
      'COMMON.TIMEOUT_WITH': 'Temps d\'espera amb',
      'COMMON.TIMEOUT_WHEN': 'Temps d\'espera quan',
      'COMMON.TIMESTAMP': 'Marca de temps',
      'COMMON.TIME_INTERVAL': 'Interval de temps',
      'COMMON.AUDIT': 'Auditar',
      'COMMON.AUDIT_TIME': 'Temps d\'auditoria',
      'COMMON.SAMPLE': 'Mostra',
      'COMMON.SAMPLE_TIME': 'Temps de mostra',
      'COMMON.BUFFER': 'Buffer',
      'COMMON.BUFFER_TIME': 'Temps de buffer',
      'COMMON.BUFFER_COUNT': 'Comptador de buffer',
      'COMMON.BUFFER_WHEN': 'Buffer quan',
      'COMMON.BUFFER_TOGGLE': 'Alternar buffer',
      'COMMON.WINDOW': 'Finestra',
      'COMMON.WINDOW_TIME': 'Temps de finestra',
      'COMMON.WINDOW_COUNT': 'Comptador de finestra',
      'COMMON.WINDOW_WHEN': 'Finestra quan',
      'COMMON.WINDOW_TOGGLE': 'Alternar finestra',
      'COMMON.GROUP_BY': 'Agrupar per',
      'COMMON.GROUP_BY_TIME': 'Agrupar per temps',
      'COMMON.GROUP_BY_COUNT': 'Agrupar per comptador',
      'COMMON.GROUP_BY_WHEN': 'Agrupar quan',
      'COMMON.GROUP_BY_TOGGLE': 'Alternar agrupació',
      'COMMON.PARTITION': 'Partició',
      'COMMON.PARTITION_TIME': 'Temps de partició',
      'COMMON.PARTITION_COUNT': 'Comptador de partició',
      'COMMON.PARTITION_WHEN': 'Partició quan',
      'COMMON.PARTITION_TOGGLE': 'Alternar partició',
      'COMMON.SHARE_REPLAY': 'Compartir repetició',
      'COMMON.PUBLISH_BEHAVIOR': 'Publicar comportament',
      'COMMON.PUBLISH_REPLAY': 'Publicar repetició',
      'COMMON.PUBLISH_LAST': 'Publicar últim',
      'COMMON.PUBLISH_CONNECT': 'Publicar connexió',
      'COMMON.PUBLISH_REF_COUNT': 'Publicar referència comptador',
      'COMMON.PUBLISH_MULTICAST': 'Publicar multicast',
      'COMMON.PUBLISH_SHARE': 'Publicar compartir',
      'COMMON.PUBLISH_REPLAY_REF_COUNT': 'Publicar repetició referència comptador',
      'COMMON.PUBLISH_BEHAVIOR_REF_COUNT': 'Publicar comportament referència comptador',
      'COMMON.PUBLISH_LAST_REF_COUNT': 'Publicar últim referència comptador',
      'COMMON.PUBLISH_CONNECT_REF_COUNT': 'Publicar connexió referència comptador',
      'COMMON.PUBLISH_MULTICAST_REF_COUNT': 'Publicar multicast referència comptador',
      'COMMON.PUBLISH_SHARE_REF_COUNT': 'Publicar compartir referència comptador',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR': 'Publicar repetició comportament',
      'COMMON.PUBLISH_REPLAY_LAST': 'Publicar repetició últim',
      'COMMON.PUBLISH_REPLAY_CONNECT': 'Publicar repetició connexió',
      'COMMON.PUBLISH_REPLAY_MULTICAST': 'Publicar repetició multicast',
      'COMMON.PUBLISH_REPLAY_SHARE': 'Publicar repetició compartir',
      'COMMON.PUBLISH_BEHAVIOR_LAST': 'Publicar comportament últim',
      'COMMON.PUBLISH_BEHAVIOR_CONNECT': 'Publicar comportament connexió',
      'COMMON.PUBLISH_BEHAVIOR_MULTICAST': 'Publicar comportament multicast',
      'COMMON.PUBLISH_BEHAVIOR_SHARE': 'Publicar comportament compartir',
      'COMMON.PUBLISH_LAST_CONNECT': 'Publicar últim connexió',
      'COMMON.PUBLISH_LAST_MULTICAST': 'Publicar últim multicast',
      'COMMON.PUBLISH_LAST_SHARE': 'Publicar últim compartir',
      'COMMON.PUBLISH_CONNECT_MULTICAST': 'Publicar connexió multicast',
      'COMMON.PUBLISH_CONNECT_SHARE': 'Publicar connexió compartir',
      'COMMON.PUBLISH_MULTICAST_SHARE': 'Publicar multicast compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST': 'Publicar repetició comportament últim',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_CONNECT': 'Publicar repetició comportament connexió',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_MULTICAST': 'Publicar repetició comportament multicast',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_SHARE': 'Publicar repetició comportament compartir',
      'COMMON.PUBLISH_REPLAY_LAST_CONNECT': 'Publicar repetició últim connexió',
      'COMMON.PUBLISH_REPLAY_LAST_MULTICAST': 'Publicar repetició últim multicast',
      'COMMON.PUBLISH_REPLAY_LAST_SHARE': 'Publicar repetició últim compartir',
      'COMMON.PUBLISH_REPLAY_CONNECT_MULTICAST': 'Publicar repetició connexió multicast',
      'COMMON.PUBLISH_REPLAY_CONNECT_SHARE': 'Publicar repetició connexió compartir',
      'COMMON.PUBLISH_REPLAY_MULTICAST_SHARE': 'Publicar repetició multicast compartir',
      'COMMON.PUBLISH_BEHAVIOR_LAST_CONNECT': 'Publicar comportament últim connexió',
      'COMMON.PUBLISH_BEHAVIOR_LAST_MULTICAST': 'Publicar comportament últim multicast',
      'COMMON.PUBLISH_BEHAVIOR_LAST_SHARE': 'Publicar comportament últim compartir',
      'COMMON.PUBLISH_BEHAVIOR_CONNECT_MULTICAST': 'Publicar comportament connexió multicast',
      'COMMON.PUBLISH_BEHAVIOR_CONNECT_SHARE': 'Publicar comportament connexió compartir',
      'COMMON.PUBLISH_BEHAVIOR_MULTICAST_SHARE': 'Publicar comportament multicast compartir',
      'COMMON.PUBLISH_LAST_CONNECT_MULTICAST': 'Publicar últim connexió multicast',
      'COMMON.PUBLISH_LAST_CONNECT_SHARE': 'Publicar últim connexió compartir',
      'COMMON.PUBLISH_LAST_MULTICAST_SHARE': 'Publicar últim multicast compartir',
      'COMMON.PUBLISH_CONNECT_MULTICAST_SHARE': 'Publicar connexió multicast compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST_CONNECT': 'Publicar repetició comportament últim connexió',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST_MULTICAST': 'Publicar repetició comportament últim multicast',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST_SHARE': 'Publicar repetició comportament últim compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_CONNECT_MULTICAST': 'Publicar repetició comportament connexió multicast',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_CONNECT_SHARE': 'Publicar repetició comportament connexió compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_MULTICAST_SHARE': 'Publicar repetició comportament multicast compartir',
      'COMMON.PUBLISH_REPLAY_LAST_CONNECT_MULTICAST': 'Publicar repetició últim connexió multicast',
      'COMMON.PUBLISH_REPLAY_LAST_CONNECT_SHARE': 'Publicar repetició últim connexió compartir',
      'COMMON.PUBLISH_REPLAY_LAST_MULTICAST_SHARE': 'Publicar repetició últim multicast compartir',
      'COMMON.PUBLISH_REPLAY_CONNECT_MULTICAST_SHARE': 'Publicar repetició connexió multicast compartir',
      'COMMON.PUBLISH_BEHAVIOR_LAST_CONNECT_MULTICAST': 'Publicar comportament últim connexió multicast',
      'COMMON.PUBLISH_BEHAVIOR_LAST_CONNECT_SHARE': 'Publicar comportament últim connexió compartir',
      'COMMON.PUBLISH_BEHAVIOR_LAST_MULTICAST_SHARE': 'Publicar comportament últim multicast compartir',
      'COMMON.PUBLISH_BEHAVIOR_CONNECT_MULTICAST_SHARE': 'Publicar comportament connexió multicast compartir',
      'COMMON.PUBLISH_LAST_CONNECT_MULTICAST_SHARE': 'Publicar últim connexió multicast compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST_CONNECT_MULTICAST': 'Publicar repetició comportament últim connexió multicast',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST_CONNECT_SHARE': 'Publicar repetició comportament últim connexió compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_LAST_MULTICAST_SHARE': 'Publicar repetició comportament últim multicast compartir',
      'COMMON.PUBLISH_REPLAY_BEHAVIOR_CONNECT_MULTICAST_SHARE': 'Publicar repetició comportament connexió multicast compartir',
      'COMMON.PUBLISH_REPLAY_LAST_CONNECT_MULTICAST_SHARE': 'Publicar repetició últim connexió multicast compartir',
      'BOOKING.LOADING_SERVICES': 'Carregant serveis...'
    });
  }
}

// Configure TestBed with TranslateModule
export function configureTestBedWithTranslate(components: unknown[] = [], additionalProviders: unknown[] = []) {
  return TestBed.configureTestingModule({
    imports: [
      ...components,
      TranslateModule.forRoot({
        loader: { provide: TranslateLoader, useClass: MockTranslateLoader }
      })
    ],
    providers: additionalProviders,
  });
}
