name: Angular Coverage with Coveralls

on:
  push:
    branches: [dev, master]
  pull_request:

jobs:
  test-and-coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Chromium
        run: sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium

      - name: Run unit tests with coverage
        env:
          CI: true
        run: npm run test:ci

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
          parallel: true

  finish:
    needs: test-and-coveralls
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
